name: figureflow
channels:
  - conda-forge
dependencies:
  - matplotlib=3.3.4
  - moviepy=1.0.3
  - numpy=1.20.3
  - pandas=1.3.0
  - pillow=8.3.1
  - pyqt>=5.9.2
  - python-pptx=0.6.21
  - scikit-image=0.18.1
  - scikit-posthocs=0.7.0
  - scipy=1.6.2
  - seaborn=0.11.1
  - tifffile=2021.4.8
  - pyarrow
