name: figureflow
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argh=0.26.2
  - arrow=0.13.1
  - astroid=2.6.5
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.6
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - binaryornot=0.4.4
  - black=19.10b0
  - blas=1.0
  - bleach=3.3.1
  - blosc=1.21.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - click=8.0.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cookiecutter=1.7.2
  - cryptography=3.4.7
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.7.0
  - decorator=4.4.2
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.3
  - ffmpeg=4.2.2
  - flake8=3.9.0
  - freetype=2.10.4
  - fsspec=2021.7.0
  - future=0.18.2
  - giflib=5.2.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagecodecs=2021.6.8
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.7
  - imagesize=1.2.0
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - inflection=0.5.1
  - intel-openmp=2021.3.0
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - isort=5.9.2
  - jedi=0.17.2
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - keyring=23.0.1
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libdeflate=1.7
  - libiconv=1.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.2.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - locket=0.2.1
  - lxml=4.8.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - moviepy=1.0.3
  - mypy_extensions=0.4.3
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.6.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1q
  - packaging=21.0
  - pandas=1.3.0
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.7.0
  - partd=1.2.0
  - pathspec=0.7.0
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare
  - pillow=8.3.1
  - pip=21.1.3
  - pluggy=0.13.1
  - poyo=0.5.0
  - proglog=0.1.9
  - prompt-toolkit=3.0.17
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=6.1.1
  - pyflakes=2.2.0
  - pygments=2.9.0
  - pylint=2.9.5
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.2
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-pptx=0.6.21
  - python-slugify=5.0.2
  - python_abi=3.9=2_cp39
  - pytz=2021.1
  - pywavelets=1.1.1
  - pywin32=228
  - pywin32-ctypes=0.2.0000
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - regex=2021.7.6
  - requests=2.25.1
  - rope=0.19.0
  - rtree=0.9.7
  - scikit-image=0.18.1
  - scikit-posthocs=0.7.0
  - scipy=1.6.2
  - seaborn=0.11.1
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - sortedcontainers=2.4.0
  - sphinx=4.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.0.5
  - spyder-kernels=2.0.5
  - sqlite=3.36.0
  - statsmodels=0.13.2
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tifffile=2021.4.8
  - tinycss
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - ujson=4.0.2
  - unidecode=1.2.0
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - whichcraft=0.6.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - xlsxwriter=3.0.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.3
  - zfp=0.5.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - tqdm=4.62.0
